Document: glancepush-vmcatcher
Title: Debian glancepush-vmcatcher Manual
Author: <insert document author here>
Abstract: This manual describes what glancepush-vmcatcher is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glancepush-vmcatcher/glancepush-vmcatcher.sgml.gz

Format: postscript
Files: /usr/share/doc/glancepush-vmcatcher/glancepush-vmcatcher.ps.gz

Format: text
Files: /usr/share/doc/glancepush-vmcatcher/glancepush-vmcatcher.text.gz

Format: HTML
Index: /usr/share/doc/glancepush-vmcatcher/html/index.html
Files: /usr/share/doc/glancepush-vmcatcher/html/*.html
